version: '3.1'

# Volume – дисковое пространство между HostOS и ContainerOS. Проще – это папка на вашей локальной машине примонтированная внутрь контейнера.
volumes: # Объявим volumes, которые будут доступны в сервисах
  redis:
  postgres-data:

services:
  db:
    image: postgres:10 # В качестве образа сервиса используется официальный образ Postgresql из Docker Hub
    expose:
      - 5432 # Выделяем для postgres 5432-ый порт контейнера
    environment: # Указываем список глобальных ENV-переменных внутри текущего контейнера
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nekko_development
    ports:
      - 127.0.0.1:5432:5432 # открываем доступ к localhost
    volumes:
      - postgres-data:/var/lib/postgresql/data # Все данные из директории data буду ложиться в volume `postgres`
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"] # Команда для проверки состояния сервиса

  in_memory_store:
    image: redis:4-alpine # В качестве образа сервиса используется официальный образ Redis из Docker Hub
    expose:
      - 6379 # Выделяем для redis 6379-ый порт контейнера
    volumes:
      - redis:/var/lib/redis/data
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "localhost", "ping"]

  server_app: &server_app
    image: nekkoru/webserver:${WEBSERVER_TAG:-latest}
    build: . # В качестве образа будет использоваться Dockerfile в текущей директории
    command: bundle exec rails server -b 0.0.0.0 # переопределяем команду запуска контейнера
    entrypoint: "./docker-entrypoint.sh" # указываем какую команду нужно запустить перед тем как контейнер запустится
    volumes:
      - .:/home/www/nekko # Указываем, что директория приложения в контейнере будет ссылаться на директорию приложения на Host OS (локальная нода). Таким образом, при изменение файлов из app или других директорий на вашей локальной машине, все изменения так же будут применены и на контейнер с данным сервисом.
#      - /home/www/nekko/vendor/bundle # Исключаем монтирование установленных гемов в контейнер
#      - /home/www/nekko/public/assets # Исключаем монтирование сгенерированых assets в контейнер
    tty: true # Открываем доступ для деббагинга контейнера
    stdin_open: true # Открываем доступ для деббагинга контейнера
    restart: on-failure # Перезапустить контейнер в случае ошибки
    environment:
      RAILS_ENV: development
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: nekko_development
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      REDIS_DB: "redis://in_memory_store:6379"
      SECRET_KEY_BASE: STUB
      DEVISE_SECRET_KEY: STUB
    depends_on: # Указываем список сервисов от которых зависит текущий сервис. Текущий сервис будет запущен только после того как запустятся зависимые сервисы
      - db
      - in_memory_store
    ports:
      - 3000:3000 # Указываем что порт из контейнера будет проксироваться на порт HostOS (HostPort:ContainerPort)
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
