version: 2
jobs:
  lint:
    working_dirictory: ~/repo
    docker:
      - image: circleci/ruby:2.6.3-node-browsers
        environment:
          PGUSER: postgres
          PGHOST: 127.0.0.1
          RAILS_ENV: test
      - image: postgres:9.5
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: website_test
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "website/Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            cd website
            gem install bundler
            bundle install --jobs=4 --retry=3 --path vendor/bundle
            gem install rubocop

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "website/Gemfile.lock" }}

      - run: cd website && rubocop

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - lint
      # todo: add test, build docker and push to registry, deploy
